### ISSUE TITLE
can not achieve psnr as the paper given

### ISSUE THREAD

**Issue by Kanbo0409** [nmhkahn/CARN-pytorch#1]
@nmhkahn Thank you for Release codes, however, when test pretrained model that you released, the psnr and ssim results are lower than the paper, for example, Set5, it achieved average psrn 29.665, ssim 0.854,  could you offer you testing configuration?

follow is the testing codes that I add in sample.py after 102 line
      hr_ = hr.cpu().mul(255).clamp(0, 255).byte().permute(1, 2, 0).numpy()
        sr_ = sr.cpu().mul(255).clamp(0, 255).byte().permute(1, 2, 0).numpy()
        im1 = hr_
        im2 = sr_
        v1 = psnr(im1,im2)
        v2 = ssim(im1,im2)
        psnrs += v1
        ssims += v2
        count += 1

        print('psnr: %.3f, ssim: %.3f'%(v1,v2))
    print('avg psnr: %.3f, avg ssim: %.3f' % (psnrs/count, ssims/count))

**Comment by nmhkahn** [comment]
Hi.

The evaluation metrics in my codes calculate PSNR or SSIM **over the RGB channels**.
But the most popular way is calculate only for the luminance channel. (Many SR papers mention about this point in their evaluation section.)

So, just see the PSNR and SSIM value in my code for the validation only.
Maybe you can get the PSNR after converting to luminance channel using like skimage library. But it seems like that converting RGB to luminance channel results different values compared to the MATLAB.

So if you want to evaluate it precisely, [this repo](https://github.com/jbhuang0604/SelfExSR/tree/master/quant_eval) will be helpful, even it's written in MATLAB.

**Comment by Kanbo0409** [comment]
Thank you @nmhkahn, another question,  I used the codes you released to train a carn_m model, however, the model I trained is 4.0MB, the pre-trained model is 1.2MB,  both model has same parameters, why?

**Comment by nmhkahn** [comment]
Well, did you follow the settings of CARN-M in README.md?
Or I think it will be helpful if you upload your settings in here.

**Comment by Kanbo0409** [comment]
@nmhkahn  My training settings as follows:
   parser = argparse.ArgumentParser()
    parser.add_argument("--model", default='carn_m', type=str)
    parser.add_argument("--ckpt_name", default='carn_m', type=str)
    
    parser.add_argument("--print_interval", type=int, default=1000)
    parser.add_argument("--train_data_path", type=str, 
                        default="../dataset/DIV2K_train.h5")
    parser.add_argument("--ckpt_dir",type=str,
                        default="../checkpoint")
    parser.add_argument("--sample_dir", type=str,
                        default="sample/")
    
    parser.add_argument("--num_gpu", type=int, default=2)
    parser.add_argument("--shave", type=int, default=20)
    parser.add_argument("--scale", type=int, default=0)

    parser.add_argument("--verbose", action="store_true", default="store_true")

    parser.add_argument("--group", type=int, default=4)
    parser.add_argument("--reduce_upsample", action="store_true", default=False)
    
    parser.add_argument("--patch_size", type=int, default=48)
    parser.add_argument("--batch_size", type=int, default=21)
    parser.add_argument("--max_steps", type=int, default=500000)
    parser.add_argument("--decay", type=int, default=300000)
    parser.add_argument("--lr", type=float, default=0.0001)
    parser.add_argument("--clip", type=float, default=10.0)

    parser.add_argument("--loss_fn", type=str, 
                        choices=["MSE", "L1", "SmoothL1"], default="L1")

**Comment by nmhkahn** [comment]
`reduce_sample` args should be `True` as below:
```python
parser.add_argument("--reduce_upsample", action="store_true", default=True)
```

**Comment by Kanbo0409** [comment]
another question, in carn_m.py line 46-47, how to obtain the mean values (0.4488, 0.4371, 0.4040) for rgb channels?

**Comment by nmhkahn** [comment]
The value (0.4488, 0.4371, 0.4040) is the mean pixels of the DIV2K dataset. We borrow this value from EDSR-pytorch. Please see [mdsr.py#L18](https://github.com/thstkdgus35/EDSR-PyTorch/blob/66494409cad7ea8ae325867ffbd6b5e8891fe17a/code/model/mdsr.py#L18).
BTW, we change some training procedure and internal status. I'll update readme docs asap.
The main differences are:

- We remove `reduce_sample` argument. Instead, we apply group convolution on the upsample block in CARN-M model.
- We increase the batch size and patch size 64 and 64 in training. Since we train using two TITAN GPU,  reduce the batch size if OOM occur.

Thanks!

**Comment by feiyangha** [comment]
@nmhkahn Hi, I got the same  psnr/ssim results with your new table. But I calculated PSNR or SSIM over the  illumination channels not the RGB channels. Did you really calculate over the RGB channels?  It puzzled me. Thanks!

**Comment by feiyangha** [comment]
@nmhkahn Hi, I got the same psnr/ssim results as your new table. But I calculated PSNR or SSIM over the illumination channels not the RGB channels. Did you really calculate over the RGB channels? It puzzled me. Thanks!

**Comment by nmhkahn** [comment]
@feiyangha Yes, I calculated metrics over the Y channel only. In the above answer https://github.com/nmhkahn/CARN-pytorch/issues/1#issuecomment-393170399, means that "I calculated over the RGB in the periodic evaluation during training (which will log to the tensorboard), but you should calculate over the Y channel if you want to reproduce my result."

**Comment by feiyangha** [comment]
I got it. Thank you!  @nmhkahn
