### ISSUE TITLE
How do you  count Mult-Adds and Params

### ISSUE THREAD

**Issue by paullu** [nmhkahn/CARN-pytorch#15]

**Comment by nmhkahn** [comment]
Check the [torchsummaryX](https://github.com/nmhkahn/torchsummaryX).
Params depend on the channels and kernel size, and mult-adds are related to the params and feature size.

**Comment by Auth0rM0rgan** [comment]
Hey @nmhkahn, 
I have a question about multiAdds. MultiAdds usually calculated by` num_params X input_height X input_width `. For example to calculating the multiAdds of CARN-M on scale X2 should be as follow if I am not wrong: 412 * 640 * 320 ~ 94.9G and also for CARN should be 1592 * 640 * 320 ~326G which is different with the results you provided in your paper. Would you please tell me how did you count MultiAdds of your models?

**Comment by nmhkahn** [comment]
@Auth0rM0rgan I don't understand how 412 and 1592 come, and input image shape is 640 * 360. Could you elaborate a little bit?

**Comment by Auth0rM0rgan** [comment]
Hey @nmhkahn,
 
412 and 1592 is the number of parameters (CARN-M and CARN). The original input size is 1280 x 720 and if we want to calculate the MultiAdds for scale 2, we have to divide input size by 2 so it's 640 * 360 then the MultiAdds for scale 2 should find by num_params * 640 * 360. Am I right?

**Comment by nmhkahn** [comment]
1592 is the total number of the parameters include upsample block. And CARN family have multiple upsample block in one network and use one of block depends on the desired scale factor.

So, consider above assumption you should multiply 64*64*18 (18 conv layers) instead of 1592. Of course don't forget to add multadds from upsample block and final conv layer.

**Comment by Yannis1995** [comment]
Hello, When i import torchsummaryX to compute the mult-add, there comes a problem:
Traceback (most recent call last):
  File "../CARN-pytorch-master/carn/train.py", line 54, in <module>
    main(cfg)
  File "/home/yyt/yyt/CARN-pytorch-master/carn/train.py", line 48, in main
    summary(net, torch.zeros(3, 1280, 720).cuda)
  File "../anaconda3/envs/pytorch_1.0/lib/python3.7/site-packages/torchsummaryX/torchsummaryX.py", line 78, in summary
    module_names = get_names_dict(model)
  File "../anaconda3/envs/pytorch_1.0/lib/python3.7/site-packages/torchsummaryX/torchsummaryX.py", line 146, in get_names_dict
    _get_names(model)
  File "/home/yyt/anaconda3/envs/pytorch_1.0/lib/python3.7/site-packages/torchsummaryX/torchsummaryX.py", line 134, in _get_names
    for key, m in module.named_children():
TypeError: named_children() missing 1 required positional argument: 'self'

**Comment by nmhkahn** [comment]
Hi @Yannis1995 
Could you paste the code snippet from network initialization to the summary part?
To me, it works well and not sure but in case you pass the network "class" not "object" into the summary function than this error can be rise.
