### ISSUE TITLE
Question about the structure of Residual-E Block 

### ISSUE THREAD

**Issue by BaiYu0120** [nmhkahn/CARN-pytorch#17]
hi.
The structure of Residual-E block was evolved from Residual Block in your paper.
Why did not arrange one more 1x1 conv between the 1st Relu and the 2nd Group Conv, only arranged one 1x1 Conv at the end of the block?

**Comment by nmhkahn** [comment]
Hi.
We decided to remove the intermediary 1x1 convolution layer to squeeze the number of the parameters.
For example, for the B=U=3 setting, adding extra 1x1 convolution in each block requires more than 35K parameters which are almost 10% of the original CARN-M model.
Of course, for the cases that performance is more important than efficiency, your suggestion can be considerable depending on the situation.
