### ISSUE TITLE
issue about number of parameters

### ISSUE THREAD

**Issue by Ji-qing** [nmhkahn/CARN-pytorch#20]
Hi, thanks for your sharing.
Which method parameters are calculated by you?

**Comment by nmhkahn** [comment]
We followed the idea of MobileNet, or you could use [torchsummaryX](https://github.com/nmhkahn/torchsummaryX).

**Comment by Ji-qing** [comment]
Thank you for your reply. It is really useful.

**Comment by feiyangha** [comment]
Hi，I use torchsummaryX to compute parameters of carn. But i got  different parameters(1111K) compared with paper. 
Thanks.
