### ISSUE TITLE
Train Loader

### ISSUE THREAD

**Issue by Auth0rM0rgan** [nmhkahn/CARN-pytorch#22]
Hi @nmhkahn,

I'm reading your code line by line to understand better and have a question about the length of `self.train_loader()` in the solver.py line 36. 

In the line below I checked the length and its 800(since we have 800 images)
```
self.train_data = TrainDataset(cfg.train_data_path, 
                                       scale=cfg.scale, 
                                       size=cfg.patch_size)
```
But after loading your `self.train_data` with` DataLoader` the length of `self.train_loader` become 25. I am curious why 25? shouldn't be still 800? 
```
self.train_loader = DataLoader(self.train_data,
                                       batch_size=cfg.batch_size,
                                       num_workers=1,
                                       shuffle=True, drop_last=True)
```
Thanks in advance!

**Comment by nmhkahn** [comment]
Did you set the batch size as 32? In that case, the length of dataloader can be 25 (=800/32).
