### ISSUE TITLE
why init_weights(modules) is empty？

### ISSUE THREAD

**Issue by go2sea** [nmhkahn/CARN-pytorch#3]
Thank you for Release codes. But i find that the function init_weights in carn/model/ops.py is empty. Is there any implementation I can follow?

**Comment by nmhkahn** [comment]
Hi.
We use pytorch default [weight_init](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/conv.py#L43) way. We left `init_weight`  function as empty because in our experiments, default init method is the best.
