### ISSUE TITLE
about training datasets

### ISSUE THREAD

**Issue by ChChwang** [nmhkahn/CARN-pytorch#30]
what's the training dataset? there are 291 images, Berkeley Segmentation, and DIV2K in the paper, but the git only has DIV2K, thanks.

**Comment by nmhkahn** [comment]
The final version of the model only uses DIV2K dataset, sorry for the confusing description in the paper.

**Comment by ChChwang** [comment]
> The final version of the model only uses DIV2K dataset, sorry for the confusing description in the paper.

how many epochs did you trained can reach the paper's performance? thanks

**Comment by nmhkahn** [comment]
About 600K iterations. We do not split DIV2K image as a small patch, rather randomly crop on-the-fly (see dataset.py), so we didn't count "epoch".

**Comment by ChChwang** [comment]
> About 600K iterations. We do not split DIV2K image as a small patch, rather randomly crop on-the-fly (see dataset.py), so we didn't count "epoch".

the PSNR on the papre was evaluated in RGB channel? or use Y in YCbCR like others? thanks a lot

**Comment by nmhkahn** [comment]
Y only like others. And you should measure using matlab.
