### ISSUE TITLE
Unexpected key(s) in state_dict: "upsample.up.body.0.weight", "upsample.up.body.0.bias"

### ISSUE THREAD

**Issue by ChChwang** [nmhkahn/CARN-pytorch#31]
can I train the x2 model via setting the scale=2? But when I test the model, an error raised,
Unexpected key(s) in state_dict: "upsample.up.body.0.weight", "upsample.up.body.0.bias"

**Comment by nmhkahn** [comment]
Could you describe the train/test arguments?
You must switch the `multi_scale` arg as False in case you wanna train on a single scale.
But if you already trained with `multi_scale=True`, you should match the consistency of this argument in test time as well.

**Comment by ChChwang** [comment]
> Could you describe the train/test arguments?
> You must switch the `multi_scale` arg as False in case you wanna train on a single scale.
> But if you already trained with `multi_scale=True`, you should match the consistency of this argument in test time as well.

oh yes, I change the test code sample.py：net = module.Net(scale=2,group=cfg.group) and it works.
