### ISSUE TITLE
Typo readme.md

### ISSUE THREAD

**Issue by materdd** [nmhkahn/CARN-pytorch#33]
Thanks for your work.
And i found the typo in readme.md (--model), please modify it.

For CARN-M
$ python carn/train.py --patch_size 64 \
                       --batch_size 64 \
                       --max_steps 600000 \
                       --decay 400000 \

> --model carn \      ->    --model carn_m \

--ckpt_name carn_m \
                       --ckpt_dir checkpoint/carn_m \
                       --scale 0 \
                       --group 4 \
                       --num_gpu 2

**Comment by nmhkahn** [comment]
Thanks! I updated it.
