### ISSUE TITLE
Calculate model parameters

### ISSUE THREAD

**Issue by lpc777** [nmhkahn/CARN-pytorch#35]
Excuse me, I want to compare with your method in my paper. I use some tools in github to calculate the model parameters, multi-Add, Flops. But I cannot get the same result. Can you give me some detailed information about calculating model parameters? thanks

**Comment by nmhkahn** [comment]
Hi. What tool did you use? and could you explain how the numbers differ?

**Comment by lpc777** [comment]
I use torchstat, here is the result :
_[MAdd]: PixelShuffle is not supported!
[Flops]: PixelShuffle is not supported!
[Memory]: PixelShuffle is not supported!
              module name  input shape output shape    params memory(MB)               MAdd              Flops   MemRead(B)  MemWrite(B) duration[%]     MemR+W(B)
0                   entry    3 480 480   64 480 480    1792.0      56.25      796,262,400.0      412,876,800.0    2771968.0   58982400.0       1.27%  6.175437e+07
1            b1.b1.body.0   64 480 480   64 480 480   36928.0      56.25   16,986,931,200.0    8,508,211,200.0   59130112.0   58982400.0       3.30%  1.181125e+08
2            b1.b1.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.21%  1.179648e+08
3            b1.b1.body.2   64 480 480   64 480 480   36928.0      56.25   16,986,931,200.0    8,508,211,200.0   59130112.0   58982400.0       2.60%  1.181125e+08
4            b1.b2.body.0   64 480 480   64 480 480   36928.0      56.25   16,986,931,200.0    8,508,211,200.0   59130112.0   58982400.0       2.75%  1.181125e+08
5            b1.b2.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.21%  1.179648e+08
6            b1.b2.body.2   64 480 480   64 480 480   36928.0      56.25   16,986,931,200.0    8,508,211,200.0   59130112.0   58982400.0       3.77%  1.181125e+08
7            b1.b3.body.0   64 480 480   64 480 480   36928.0      56.25   16,986,931,200.0    8,508,211,200.0   59130112.0   58982400.0       2.75%  1.181125e+08
8            b1.b3.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.21%  1.179648e+08
9            b1.b3.body.2   64 480 480   64 480 480   36928.0      56.25   16,986,931,200.0    8,508,211,200.0   59130112.0   58982400.0       2.67%  1.181125e+08
10           b1.c1.body.0  128 480 480   64 480 480    8256.0      56.25    3,774,873,600.0    1,902,182,400.0  117997824.0   58982400.0       2.10%  1.769802e+08
11           b1.c1.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.22%  1.179648e+08
12           b1.c2.body.0  192 480 480   64 480 480   12352.0      56.25    5,662,310,400.0    2,845,900,800.0  176996608.0   58982400.0       2.80%  2.359790e+08
13           b1.c2.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.21%  1.179648e+08
14           b1.c3.body.0  256 480 480   64 480 480   16448.0      56.25    7,549,747,200.0    3,789,619,200.0  235995392.0   58982400.0       3.17%  2.949778e+08
15           b1.c3.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.21%  1.179648e+08
16           b2.b1.body.0   64 480 480   64 480 480   36928.0      56.25   16,986,931,200.0    8,508,211,200.0   59130112.0   58982400.0       2.58%  1.181125e+08
17           b2.b1.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.20%  1.179648e+08
18           b2.b1.body.2   64 480 480   64 480 480   36928.0      56.25   16,986,931,200.0    8,508,211,200.0   59130112.0   58982400.0       2.54%  1.181125e+08
19           b2.b2.body.0   64 480 480   64 480 480   36928.0      56.25   16,986,931,200.0    8,508,211,200.0   59130112.0   58982400.0       2.53%  1.181125e+08
20           b2.b2.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.20%  1.179648e+08
21           b2.b2.body.2   64 480 480   64 480 480   36928.0      56.25   16,986,931,200.0    8,508,211,200.0   59130112.0   58982400.0       2.52%  1.181125e+08
22           b2.b3.body.0   64 480 480   64 480 480   36928.0      56.25   16,986,931,200.0    8,508,211,200.0   59130112.0   58982400.0       2.52%  1.181125e+08
23           b2.b3.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.20%  1.179648e+08
24           b2.b3.body.2   64 480 480   64 480 480   36928.0      56.25   16,986,931,200.0    8,508,211,200.0   59130112.0   58982400.0       3.01%  1.181125e+08
25           b2.c1.body.0  128 480 480   64 480 480    8256.0      56.25    3,774,873,600.0    1,902,182,400.0  117997824.0   58982400.0       2.06%  1.769802e+08
26           b2.c1.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.21%  1.179648e+08
27           b2.c2.body.0  192 480 480   64 480 480   12352.0      56.25    5,662,310,400.0    2,845,900,800.0  176996608.0   58982400.0       2.58%  2.359790e+08
28           b2.c2.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.20%  1.179648e+08
29           b2.c3.body.0  256 480 480   64 480 480   16448.0      56.25    7,549,747,200.0    3,789,619,200.0  235995392.0   58982400.0       2.96%  2.949778e+08
30           b2.c3.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.21%  1.179648e+08
31           b3.b1.body.0   64 480 480   64 480 480   36928.0      56.25   16,986,931,200.0    8,508,211,200.0   59130112.0   58982400.0       2.51%  1.181125e+08
32           b3.b1.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.20%  1.179648e+08
33           b3.b1.body.2   64 480 480   64 480 480   36928.0      56.25   16,986,931,200.0    8,508,211,200.0   59130112.0   58982400.0       2.52%  1.181125e+08
34           b3.b2.body.0   64 480 480   64 480 480   36928.0      56.25   16,986,931,200.0    8,508,211,200.0   59130112.0   58982400.0       2.51%  1.181125e+08
35           b3.b2.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.20%  1.179648e+08
36           b3.b2.body.2   64 480 480   64 480 480   36928.0      56.25   16,986,931,200.0    8,508,211,200.0   59130112.0   58982400.0       2.56%  1.181125e+08
37           b3.b3.body.0   64 480 480   64 480 480   36928.0      56.25   16,986,931,200.0    8,508,211,200.0   59130112.0   58982400.0       2.54%  1.181125e+08
38           b3.b3.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.20%  1.179648e+08
39           b3.b3.body.2   64 480 480   64 480 480   36928.0      56.25   16,986,931,200.0    8,508,211,200.0   59130112.0   58982400.0       2.52%  1.181125e+08
40           b3.c1.body.0  128 480 480   64 480 480    8256.0      56.25    3,774,873,600.0    1,902,182,400.0  117997824.0   58982400.0       2.01%  1.769802e+08
41           b3.c1.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.20%  1.179648e+08
42           b3.c2.body.0  192 480 480   64 480 480   12352.0      56.25    5,662,310,400.0    2,845,900,800.0  176996608.0   58982400.0       2.86%  2.359790e+08
43           b3.c2.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.21%  1.179648e+08
44           b3.c3.body.0  256 480 480   64 480 480   16448.0      56.25    7,549,747,200.0    3,789,619,200.0  235995392.0   58982400.0       2.99%  2.949778e+08
45           b3.c3.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.21%  1.179648e+08
46              c1.body.0  128 480 480   64 480 480    8256.0      56.25    3,774,873,600.0    1,902,182,400.0  117997824.0   58982400.0       2.12%  1.769802e+08
47              c1.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.21%  1.179648e+08
48              c2.body.0  192 480 480   64 480 480   12352.0      56.25    5,662,310,400.0    2,845,900,800.0  176996608.0   58982400.0       2.51%  2.359790e+08
49              c2.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.20%  1.179648e+08
50              c3.body.0  256 480 480   64 480 480   16448.0      56.25    7,549,747,200.0    3,789,619,200.0  235995392.0   58982400.0       2.98%  2.949778e+08
51              c3.body.1   64 480 480   64 480 480       0.0      56.25       14,745,600.0       14,745,600.0   58982400.0   58982400.0       0.21%  1.179648e+08
52     upsample.up.body.0   64 480 480  256 480 480  147712.0     225.00   67,947,724,800.0   34,032,844,800.0   59573248.0  235929600.0       9.03%  2.955028e+08
53     upsample.up.body.1  256 480 480  256 480 480       0.0     225.00       58,982,400.0       58,982,400.0  235929600.0  235929600.0       0.84%  4.718592e+08
54     upsample.up.body.2  256 480 480   64 960 960       0.0     225.00                0.0                0.0          0.0          0.0       1.88%  0.000000e+00
55                   exit   64 960 960    3 960 960    1731.0      10.55    3,185,049,600.0    1,595,289,600.0  235936524.0   11059200.0       2.81%  2.469957e+08
total                                                964163.0    3610.55  446,010,163,200.0  223,708,262,400.0  235936524.0   11059200.0     100.00%  8.511146e+09
==================================================================================================================================================================
Total params: 964,163
------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total memory: 3610.55MB
Total MAdd: 446.01GMAdd
Total Flops: 223.71GFlops
Total MemR+W: 7.93GB_

**Comment by nmhkahn** [comment]
It because the original CARN includes [2, 3, 4] upsample block at the same time. But the tool you used only considers the module that propagated when calculating params, in other words, it only calculates x2 upsample block.

**Comment by lpc777** [comment]
OK, I get it. Thank you very much!
