### ISSUE TITLE
MeanShift(nn.Module):

### ISSUE THREAD

**Issue by huangyangpi** [nmhkahn/CARN-pytorch#40]
Thank you for the code you provided. I am new at SR. I have a question when reading the code.why do we do MeanShift processing? What is the significance？

class MeanShift(nn.Module):
    def __init__(self, mean_rgb, sub):
        super(MeanShift, self).__init__()

        sign = -1 if sub else 1
        r = mean_rgb[0] * sign
        g = mean_rgb[1] * sign
        b = mean_rgb[2] * sign

        self.shifter = nn.Conv2d(3, 3, 1, 1, 0)
        self.shifter.weight.data = torch.eye(3).view(3, 3, 1, 1)  
        self.shifter.bias.data = torch.Tensor([r, g, b])

        # Freeze the mean shift layer
        for params in self.shifter.parameters():
            params.requires_grad = False

    def forward(self, x):
        x = self.shifter(x)
        return x

**Comment by nmhkahn** [comment]
Hi. MeanShift module makes the input image to be zero-centered (see [here](https://github.com/thstkdgus35/EDSR-PyTorch/issues/94)). We borrowed the snippet from the EDSR-pytorch repo (except our default rgb_range is 1.0, not 255).
