### ISSUE TITLE
Different Multi-Adds on CARN-M

### ISSUE THREAD

**Issue by Yeeef** [nmhkahn/CARN-pytorch#42]
Hi,
I use `TensorSummaryX` to calculate the multiadds of your proposed CARN-M. However, the results are different from paper. The results of CARN are exactly same.

For example, the x4 multi-adds I calculated is 63G, but the paper's result is 32.5G

**Comment by nmhkahn** [comment]
@Yeeef Hi
I ran the code again and got 32.5G MultAdds as well.
Could you explain the setting you used?

**Comment by Yeeef** [comment]
My bad. I forgot to set the `group=4` in Upsample Block.

Thanks for your quick reply and great work!
