### ISSUE TITLE
question about  the network's parameters

### ISSUE THREAD

**Issue by yuqiangchu** [nmhkahn/CARN-pytorch#47]
Recently，I ran the code as the setting you gave.But something wrong here.So, can you tell me why the CARN's parameters I ran were 1112K with the scale set 4,and the CARN-M's parameters were 294K with the scale set 4 and the group set 4.I never change the codes.And I ran it with the settings you put in github.I am so confused.
It will be very grateful if you answer me this question.Hoping for your reply.

**Comment by nmhkahn** [comment]
The number of the params described in the paper include "all the upsample blocks" meaning that x2, x3, x4 upsampling blocks are taken account so that # params are identical for all the scale factor cases. For example, 1592-1112K=480K params in CARN is for x2 and x3 scale upsampling block.

**Comment by yuqiangchu** [comment]
Oh, I see. Thanks very much.
