### ISSUE TITLE
Out of memory error arise when test pretrained models

### ISSUE THREAD

**Issue by ThreeSevenGO** [nmhkahn/CARN-pytorch#5]
Thank you for your creative work.But when I was testing pretrained models with an image(width:960px, height:1707px)，out of memory error arise. This is confusing because my memory should be enough.   
The args are as follows.
"cuda":false,  
"group":1,  
"scale":2,  
"shave":20  
I don't know if it's reasonable. Did I have the wrong operation？

**Comment by nmhkahn** [comment]
Hi, sorry for late reply.

If your **LR** images are 2K resolution, then it could be raised OOM (of course depend on the RAM or VRAM).
The most simple way is split the test image with overlap and run SR individually. In the sample.py, I experimentally write about it and you might refer as well (see [sample.py#L38](https://github.com/nmhkahn/CARN-pytorch/blob/master/carn/sample.py#L38)).

**Comment by paullu** [comment]
Do not forget  "torch.set_grad_enabled(False)" at begining when infering. To my experience  ,it will save half memory
